# Generated by Django 2.1.1 on 2018-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=60)),
                ('date', models.CharField(help_text='YYYYMMDD', max_length=8)),
                ('content', models.TextField(blank=True, help_text='Content', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
