# Generated by Django 2.1.1 on 2018-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180913_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='newss',
            field=models.ManyToManyField(help_text='The news that has this word.', to='blog.News'),
        ),
    ]
