# Generated by Django 2.1.1 on 2018-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180913_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(default='', max_length=20),
        ),
    ]
