# Generated by Django 2.1.1 on 2018-09-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180913_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(max_length=20)),
                ('newss', models.ManyToManyField(help_text='The news that use this word.', to='blog.News')),
            ],
        ),
    ]
