# Generated by Django 2.1.1 on 2018-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spell',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
