# Generated by Django 2.1.1 on 2018-09-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180913_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='newss',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
