# Generated by Django 2.1.1 on 2018-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='newss',
        ),
        migrations.AddField(
            model_name='news',
            name='words',
            field=models.ManyToManyField(to='blog.Word'),
        ),
    ]
